language: python

python:
  - "3.6.7"
  
# install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  postgresql: "9.4"


before_script:
  - psql -c 'create database olympians;' -U postgres

# run tests

script:
  - python manage.py makemigrations authentication --settings=authors.settings.test
  - python manage.py migrate authentication --settings=authors.settings.test
  - python manage.py makemigrations profiles --settings=authors.settings.test
  - python manage.py migrate profiles --settings=authors.settings.test
  - python manage.py makemigrations article --settings=authors.settings.test
  - python manage.py migrate article --settings=authors.settings.test
  - coverage run --source=authors.apps ./manage.py test --settings=authors.settings.test
  - coverage report
    
after_success:
  - coverallslanguage: python
  - coveralls
